[[redirects]]
  from = "/api/*"
  to = "https://food-suggestion-rmit.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/"
  status = 200